version: "3.9"

services:
  api:
    build: .
    container_name: fastapi_app
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: always

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: pashantraj
      POSTGRES_PASSWORD: dbproject
      POSTGRES_DB: fastapi
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: